# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bec9eaf77234936cd3deaf8078ea86c0274aac179c29b9711011f15a0825e46969e35b99e9d3c2f1c501596b60dc8b407e77da90a44e537425aa49f8769d2b5

test:
  secret_key_base: ebfae2bc7794c18fb69ee2431d21b584fa73290254d7f3065503293b492b5efc65b8f77545d61cd41ba1c3be8d837b5df6ffad6631a9412567d96bf4f67a6ed7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
